import Foundation
import CoreML
import SwiftUI

class ArtWork: ObservableObject { // a definition of a paint and it's information
    let title: String // painting's name
    let artist: String // painting's author
    let date: String // painting's publication year
    var description: String // painting's description
    let technique: String // painting's technique
    let image: String // URL of painting's image
    var riddle: String // riddle to be solved
    var hint: String // hint to let the user to guess the painting
    @Published var guessed: Bool = false // true if the art work has been already guessed
    
    init(title: String, artist: String, date: String, description: String, technique: String, image: String, riddle: String, hint: String) {
        self.title = title
        self.artist = artist
        self.date = date
        self.description = description
        self.technique = technique
        self.image = image
        self.riddle = riddle
        self.hint = hint
    }
}

let vesuvius = ArtWork(title: "Vesuvius", artist: "Andy Warhol", date: "1985", description: "Vesuvius è una delle opere più iconiche di Andy Warhol, noto per essere uno dei più influenti artisti del movimento Pop Art. Realizzata nel 1985, l'opera raffigura il Vesuvio, il famoso vulcano situato vicino a Napoli, Italia. Warhol è famoso per aver utilizzato oggetti e immagini di massa nella sua arte, trasformando oggetti comuni in opere d'arte straordinarie. Con Vesuvius, Warhol ha reinterpretato un'icona naturalistica in uno stile distintivo pop, utilizzando colori accesi e grafiche audaci. Nell'opera, il Vesuvio è rappresentato in modo stilizzato, con contorni netti e colori vibranti. Warhol ha utilizzato una tecnica di serigrafia per creare l'opera, che è diventata una delle sue tecniche distintive. La ripetizione dell'immagine del Vesuvio in varie tonalità e colori conferisce all'opera un'impressione di vitalità e dinamismo. Vesuvius di Andy Warhol rappresenta una combinazione unica di arte contemporanea e iconografia classica, catturando l'attenzione dello spettatore con la sua potenza visiva e la sua audace reinterpretazione di un simbolo della natura.", technique: "Olio su tela", image: "Vesuvius", riddle: "In un mondo di forme audaci e colori brillanti,\n Io sto silenzioso, ma potente nei miei accenti.\n Nelle profondità dell'arte, mi troverai,\n Un'icona di massa, per sempre resterò.", hint: "Quest'opera d'arte di Andy Warhol trasforma un'icona naturale in uno stile audace e distintivo, utilizzando colori accesi e una ripetizione grafica che è diventata un marchio distintivo dell'artista.")

let flagellazioneCristo = ArtWork(title: "Flagellazione Di Cristo", artist: "Caravaggio", date: "1607", description: "La Flagellazione di Cristo è un dipinto del celebre artista italiano Caravaggio, realizzato intorno al 1607. Il dipinto è parte di una serie di opere religiose di Caravaggio che rappresentano scene della Passione di Cristo. Questa opera in particolare raffigura il momento in cui Gesù Cristo viene flagellato prima della crocifissione. Nella Flagellazione di Cristo, Caravaggio utilizza il suo stile distintivo caratterizzato da un forte contrasto tra luci e ombre, noto come chiaroscuro, per creare un'intensa drammaticità nella scena. La luce si concentra sul corpo sofferente di Cristo, mentre i soldati romani che lo torturano sono parzialmente immersi nell'ombra, creando un forte senso di realismo e pathos. Il dipinto cattura il momento di massima sofferenza fisica di Cristo durante il suo calvario, evidenziando il tema della redenzione attraverso il sacrificio. Le espressioni dei personaggi, la resa naturalistica delle figure e l'intensa rappresentazione del dolore conferiscono all'opera una potente carica emotiva. La Flagellazione di Cristo di Caravaggio è considerata una delle sue opere più iconiche e rappresentative del suo stile pittorico rivoluzionario. Si trova attualmente presso il Museo di Capodimonte a Napoli, Italia.", technique: "Olio su tela", image: "FlagellazioneCristo", riddle: "In un luogo oscuro e silente mi puoi trovare,\n Il dolore e la sofferenza mi fanno dimorare.\n Con corde e fruste mi colpiscono senza pietà,\nMa nel mio sguardo, c'è un'eterna verità.", hint: "Quest'opera di Caravaggio rappresenta un momento molto doloroso per il figlio di Dio.")

let sanGirolamo = ArtWork(title: "San Girolamo nello Studio", artist: "Colantonio", date: "1445", description: "San Girolamo nello studio di Colantonio ritrae San Girolamo, un santo noto per la sua erudizione e la sua traduzione della Bibbia in latino (la Vulgata), in una posa assorta, con lo sguardo concentrato su un testo aperto. Una delle caratteristiche più iconiche dell'opera è la presenza di un leone accanto a San Girolamo. Questo leone, simbolo della forza e del coraggio, rappresenta la leggenda secondo cui San Girolamo riuscì a domare un leone ferito tirandogli fuori una spina dalla zampa. La presenza del leone nel dipinto sottolinea la santità e il potere spirituale del santo, oltre a richiamare l'episodio leggendario della sua vita.", technique: "Olio su tavola", image: "SanGirolamo", riddle: "In un vecchio studio tranquillo e discreto,\n Un santo si perde tra i libri, concentrato e lieto.\n Chi è, dunque, quest'uomo in contemplazione?\n Colantonio l'ha dipinto con tanta dedizione.", hint: "In quest'opera, un santo è raffigurato mentre studia in un ambiente tranquillo e raccolto, insieme ad un animale feroce.")

let crocifissioneMasaccio = ArtWork(title: "Crocifissione di Masaccio", artist: "Masaccio", date: "1426", description: "La tavola dipinta da Masaccio ritrae la Madonna, san Giovanni e la Maddalena piangenti davanti al Cristo Crocifisso, in uno spazio delineato da un arco ogivale e uno sfondo dorato. Masaccio enfatizza il dolore umano, concentrando l'attenzione sulle mani contratte della Madonna, sul volto dolente di san Giovanni e sulle braccia alzate della Maddalena, senza volto. Cristo è raffigurato frontalmente, con la testa abbassata e le gambe abbreviate, suggerendo la sua umanità nell'affrontare la morte. Le figure, modellate con contrasti di luce e ombra, si inseriscono in uno spazio realistico nonostante lo sfondo dorato, creando un'atmosfera drammatica.", technique: "Olio su tavola", image: "CrocifissioneMasaccio", riddle: "In un dipinto sacro, un dramma si svela,\nLa Madonna, san Giovanni e la Maddalena, in preghiera si cela.\nBraccia alzate, mani contratte, il dolore è palpabile,\nCristo, frontale, testa china, nell'agonia inestricabile.", hint: "L’opera in questione raffigura un momento fortemente religioso. La Madonna, San Giovanni e la Maddalena piangono una quarta figura crocifissa.")

let strageInnocnti = ArtWork(title: "Strage degli Innocenti", artist: "Matteo di Giovanni", date: "1478", description: "Il dipinto ritrae la Strage degli Innocenti, un evento descritto da uno degli evangelisti, nel quale il re Erode, temendo la nascita di un potenziale rivale al trono, ordina l'uccisione di molti bambini. Erode è rappresentato come un re elegante seduto sul trono mentre dà l'ordine. I bambini, contrassegnati da aureole, simboli della loro innocenza, sono vittime impotenti della violenza regale. La scena è ricca di dettagli disordinati: soldati, armi, madri disperate e corpi di bambini straziati. Tuttavia, alcuni gruppi di figure, come le madri con i bambini o le persone in fuga, si ripresentano in opere successive, evidenziando la continuità narrativa nell'arte.", technique: "Tempera su tavola", image: "StrageInnocenti", riddle: "In un dipinto antico, un re seduto in trono,\nOrdina l'orrore, un gesto inumano.\nBambini con aureole, vittime innocenti,\nIn una scena di dolore, raffigurata con ardente fervore.", hint: "In quest'opera di Matteo di Giovanni, un re ordina l'uccisione di bambini innocenti, mentre le restanti figure vengono rappresentate sofferenti.")

let sanNicola = ArtWork(title: "San Nicola di Bari", artist: "Mattia Preti", date: "1653", description: "Il San Nicola di Bari, di Mattia Preti, suscitò ammirazione tra i pittori napoletani, nonostante la malizia che spesso si veniva a creare tra i pittori. La figura del santo è impeccabile, con le braccia distese che conferiscono solennità alla scena, suggerendo un senso di movimento verso l'alto. I colori vivaci, specialmente delle vesti degli angeli, contrastano con il fondo scuro. Le tre sfere d'oro ai piedi del santo sono un attributo iconografico classico, legato alla leggenda che narra come San Nicola abbia aiutato un vicino in povertà. La composizione si focalizza sulla figura possente del santo emergente dall'ombra, richiamando influenze della tradizione emiliana e dei naturalisti napoletani.", technique: "Olio su tela", image: "SanNicola", riddle: "Un santo in trionfo,\nCon braccia spiegate, splende in volo.\nColori accesi, contrasto con il fondo,\nLe tre sfere d'oro, un mistero profondo.", hint: "Un santo di Bari è rappresentato con grande maestria, con le braccia aperte in un gesto solenne, mentre colori accesi illuminano la scena.")
